#!/usr/bin/env bash
# Octo installer.
# Prompts for required configuration, writes .env, and brings the stack up.
# Idempotent — re-running offers to keep existing values.
set -euo pipefail

cd "$(dirname "$0")"

# ─────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────
bold()  { printf "\033[1m%s\033[0m\n" "$*"; }
green() { printf "\033[32m%s\033[0m\n" "$*"; }
red()   { printf "\033[31m%s\033[0m\n" "$*"; }
dim()   { printf "\033[2m%s\033[0m\n" "$*"; }

ask() {
  # ask "Prompt" "default" -> echoes user's answer (or default on empty)
  local prompt="$1" default="${2-}" reply
  if [ -n "$default" ]; then
    read -rp "$prompt [$default]: " reply
    echo "${reply:-$default}"
  else
    read -rp "$prompt: " reply
    echo "$reply"
  fi
}

ask_secret() {
  local prompt="$1" default="${2-}" reply
  if [ -n "$default" ]; then
    read -rsp "$prompt [keep existing]: " reply; echo
    echo "${reply:-$default}"
  else
    read -rsp "$prompt: " reply; echo
    echo "$reply"
  fi
}

random_password() {
  # 24 chars of urlsafe base64 (~144 bits entropy). No external deps needed.
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 18 | tr -d '/+=' | cut -c1-24
  else
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24
  fi
}

require_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    red "Docker not found. Install Docker first: https://docs.docker.com/engine/install/"
    exit 1
  fi
  if ! docker compose version >/dev/null 2>&1; then
    red "'docker compose' (v2) not available. Update Docker: https://docs.docker.com/compose/install/"
    exit 1
  fi
}

# ─────────────────────────────────────────────────────────────────
# Load existing .env if present so re-runs preserve values
# ─────────────────────────────────────────────────────────────────
declare -A EXISTING
if [ -f .env ]; then
  while IFS='=' read -r k v; do
    [[ "$k" =~ ^[A-Z_]+$ ]] || continue
    # Strip surrounding quotes if present
    v="${v%\"}"; v="${v#\"}"
    EXISTING[$k]="$v"
  done < .env
fi
existing() { echo "${EXISTING[$1]-}"; }

# ─────────────────────────────────────────────────────────────────
# Run
# ─────────────────────────────────────────────────────────────────
clear
bold "═══════════════════════════════════════════════════════════"
bold "  Octo · installer"
bold "═══════════════════════════════════════════════════════════"
echo
echo "This script will:"
echo "  • check Docker is installed"
echo "  • prompt for a few configuration values"
echo "  • write .env"
echo "  • bring the 3-container stack up via docker compose"
echo
require_docker
green "✓ Docker available"
echo

bold "─── Required ────────────────────────────────────────────────"
SUBSONIC_URL=$(ask "Navidrome URL (the music server Octo proxies)" "$(existing SUBSONIC_URL || echo "http://localhost:4533")")
DOWNLOAD_PATH=$(ask "Music directory on this host (mounted into the stack)" "$(existing DOWNLOAD_PATH || echo "./downloads")")

echo
bold "─── Last.fm (powers radio + discovery) ──────────────────────"
echo "Get a free API key at: https://www.last.fm/api/account/create"
LASTFM_API_KEY=$(ask "Last.fm API key (leave blank to skip — radio will be disabled)" "$(existing LASTFM_API_KEY)")

echo
bold "─── Soulseek (downloads when you star a song) ───────────────"
SLSKD_SOULSEEK_USERNAME=$(ask "Your Soulseek-network username" "$(existing SLSKD_SOULSEEK_USERNAME)")
SLSKD_SOULSEEK_PASSWORD=$(ask_secret "Your Soulseek-network password" "$(existing SLSKD_SOULSEEK_PASSWORD)")

echo
bold "─── Storage / layout ────────────────────────────────────────"
STORAGE_MODE=$(ask "Storage mode (Stream | Permanent | Cache)" "$(existing STORAGE_MODE || echo "Stream")")
FOLDER_STRUCTURE=$(ask "Folder layout for downloads (Flat | Organized)" "$(existing FOLDER_STRUCTURE || echo "Flat")")

# slskd web UI admin — auto-generate on first run, preserve on re-run
SLSKD_USERNAME="$(existing SLSKD_USERNAME || echo "admin")"
SLSKD_PASSWORD="$(existing SLSKD_PASSWORD)"
if [ -z "$SLSKD_PASSWORD" ]; then
  SLSKD_PASSWORD="$(random_password)"
  green "✓ generated random slskd web admin password"
fi

# ─────────────────────────────────────────────────────────────────
# Write .env
# ─────────────────────────────────────────────────────────────────
echo
bold "─── Writing .env ────────────────────────────────────────────"
cat > .env <<EOF
# Generated by install.sh — re-run the script to update values.
# The admin UI at http://<host>:5274/admin/ can also edit settings live.

# === Required ===
SUBSONIC_URL=$SUBSONIC_URL
DOWNLOAD_PATH=$DOWNLOAD_PATH

# === Last.fm ===
LASTFM_API_KEY=$LASTFM_API_KEY
LASTFM_ENABLE_RADIO=true
LASTFM_RADIO_TRACK_COUNT=50
LASTFM_RADIO_CACHE_HOURS=24

# === Soulseek (slskd) ===
SLSKD_USERNAME=$SLSKD_USERNAME
SLSKD_PASSWORD=$SLSKD_PASSWORD
SLSKD_SEARCH_WAIT_SECONDS=6
SLSKD_MIN_FILE_SIZE_BYTES=5242880
SLSKD_PREFERRED_EXTENSION=flac
SLSKD_DOWNLOAD_TIMEOUT_SECONDS=180
SLSKD_SOULSEEK_USERNAME=$SLSKD_SOULSEEK_USERNAME
SLSKD_SOULSEEK_PASSWORD="$SLSKD_SOULSEEK_PASSWORD"

# === Storage / layout ===
STORAGE_MODE=$STORAGE_MODE
DOWNLOAD_MODE=Track
DOWNLOAD_ON_STAR=true
FOLDER_STRUCTURE=$FOLDER_STRUCTURE
USE_LOCAL_STAGING=false
EXPLICIT_FILTER=All
CACHE_DURATION_HOURS=1
ENABLE_EXTERNAL_PLAYLISTS=false

# === yt-dlp shim (defaults are fine) ===
YTDLP_MAX_CONCURRENT=5
YTDLP_SEARCH_CACHE_MAX=1024
YTDLP_URL_CACHE_MAX=512
YTDLP_URL_CACHE_TTL=3600
EOF
chmod 600 .env
green "✓ wrote .env (chmod 600)"

# Make sure the bind-mount target exists so docker doesn't create it as root.
mkdir -p "$DOWNLOAD_PATH" "octo-config" "slskd-state"

# ─────────────────────────────────────────────────────────────────
# Build + start
# ─────────────────────────────────────────────────────────────────
echo
bold "─── Building images ─────────────────────────────────────────"
docker compose build

echo
bold "─── Starting stack ──────────────────────────────────────────"
docker compose up -d

# ─────────────────────────────────────────────────────────────────
# Wait for octo to come up
# ─────────────────────────────────────────────────────────────────
echo
echo -n "Waiting for Octo to become reachable on :5274 "
for i in $(seq 1 60); do
  if curl -s -m 2 -o /dev/null -w '%{http_code}' "http://localhost:5274/api/admin/status" 2>/dev/null | grep -q '^2'; then
    echo
    green "✓ Octo is up"
    break
  fi
  echo -n "."
  sleep 2
  if [ "$i" = "60" ]; then
    echo
    red "Octo did not respond within 2 minutes. Check 'docker compose logs octorr'."
    exit 1
  fi
done

# ─────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────
echo
bold "═══════════════════════════════════════════════════════════"
green "  Done. Open the admin UI:"
echo
bold "    http://localhost:5274/admin/"
echo
echo "  • Point your Subsonic clients at: http://<this-host>:5274"
echo "  • slskd's own web UI is at:        http://<this-host>:5030"
echo "    (login: $SLSKD_USERNAME / shown above on first run)"
echo
dim "  Stop:    docker compose down"
dim "  Update:  git pull && ./install.sh"
bold "═══════════════════════════════════════════════════════════"
