#!/usr/bin/env bash
# Tests that re-running install.sh keeps everything the user had in .env. Runs a copy of the
# installer in a throwaway folder with docker, curl, clear and sleep faked, answering every
# question with Enter, so it runs anywhere bash does (CI runs it beside shellcheck).
#   scripts/test-install.sh
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
installer="$here/../install.sh"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/bin" "$work/music"
failures=0

# docker only logs. curl answers 200 to every status code probe and a Last.fm track to the key
# check, so each question takes the default and Octo looks healthy straight away.
printf '#!/usr/bin/env bash\necho "docker $*" >> "%s/docker.log"\n' "$work" > "$work/bin/docker"
cat > "$work/bin/curl" <<'EOF'
#!/usr/bin/env bash
for arg in "$@"; do
  [ "$arg" = -w ] && { echo 200; exit 0; }
done
case "$*" in
  *audioscrobbler*) echo '{"track":{}}' ;;
  *) echo '{}' ;;
esac
EOF
printf '#!/usr/bin/env bash\nexit 0\n' > "$work/bin/clear"
printf '#!/usr/bin/env bash\nexit 0\n' > "$work/bin/sleep"
chmod +x "$work/bin/"*
export PATH="$work/bin:$PATH"

fresh() { # a copy of the installer with no .env yet
  rm -rf "$work/octo"
  mkdir -p "$work/octo/scripts/updater"
  tr -d '\r' < "$installer" > "$work/octo/install.sh"
  # Where systemd runs (CI does), the installer offers the update helper; never install it here.
  printf '#!/usr/bin/env bash\nexit 0\n' > "$work/octo/scripts/updater/install-updater.sh"
  chmod +x "$work/octo/install.sh" "$work/octo/scripts/updater/install-updater.sh"
}
printf '\n%.0s' $(seq 1 50) > "$work/answers"
run() { # answers every question with Enter
  bash "$work/octo/install.sh" < "$work/answers" > "$work/out.log" 2>&1
}
# A setting's value as Compose reads it: the last line wins, surrounding quotes come off.
value_of() {
  local line
  line="$(tr -d '\r' < "$1" | grep "^$2=" | tail -n 1)" || return 1
  line="${line#*=}"; line="${line%\"}"; echo "${line#\"}"
}
pass() { echo "ok    $1"; }
fail() { echo "FAIL  $1"; failures=$((failures + 1)); }

# An .env the way a user who has been running Octo a while might have it: everything the
# installer asks about, a default changed by hand, settings the installer has never written,
# an empty value, a value with = in it, quotes, a Windows line ending and no final newline.
fresh
cat > "$work/octo/.env" <<EOF
# Generated by install.sh, then edited by hand.
SUBSONIC_URL=http://192.168.1.20:4533
DOWNLOAD_PATH=$work/music
LASTFM_API_KEY=abc123
LASTFM_API_SECRET=s3cret=with=equals
LASTFM_ENABLE_DISCOVERY_MIX=false
LASTFM_ENABLE_YOUR_MIX=false
LASTFM_DISCOVERY_STATION_COUNT=4
LASTFM_PERSONALIZED_STATION_COUNT=6
LASTFM_RADIO_TRACK_COUNT=80
SLSKD_USERNAME=octoadmin
SLSKD_PASSWORD=webpass
SLSKD_SEARCH_WAIT_SECONDS="12"
SLSKD_SOULSEEK_USERNAME=someone
SLSKD_SOULSEEK_PASSWORD="pass word"
DOWNLOAD_SOURCE=Soulseek
STORAGE_MODE=Permanent
FOLDER_STRUCTURE=Organized
EXPLICIT_FILTER=Clean
YTDLP_GATE_RESERVE=2
YTDLP_BG_GATE_WAIT_SEC=45
OCTO_CONFIG_DIR=$work/octo-config
UPDATES_CHECK=false
UPDATES_REPO=
COMPOSE_PROFILES=sonic
EOF
printf 'Custom_Key2=kept\r\nLAST_LINE=no-newline' >> "$work/octo/.env"
cp "$work/octo/.env" "$work/before.env"

run && pass "the installer finishes" || { fail "the installer stopped early:"; tail -n 20 "$work/out.log"; }

lost=()
for key in $(grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$work/before.env" | tr -d '=' | sort -u); do
  want="$(value_of "$work/before.env" "$key")"
  got="$(value_of "$work/octo/.env" "$key")" || got="(missing)"
  [ "$got" = "$want" ] || lost+=("$key: had '$want', now '$got'")
done
[ "${#lost[@]}" = 0 ] && pass "every setting in the old .env keeps its value" || {
  fail "settings lost or changed:"; printf '        %s\n' "${lost[@]}"; }

grep -qx 'EXPLICIT_FILTER=Clean' "$work/octo/.env" && grep -qx 'LASTFM_RADIO_TRACK_COUNT=80' "$work/octo/.env" \
  && pass "a default changed by hand stays changed" || fail "a hand-changed default went back"
grep -qx 'SLSKD_SEARCH_WAIT_SECONDS="12"' "$work/octo/.env" \
  && pass "a kept line keeps its quotes" || fail "a kept line lost its quotes"
grep -qx 'UPDATES_REPO=' "$work/octo/.env" \
  && pass "an empty value is kept" || fail "an empty value was dropped"
grep -q $'\r' "$work/octo/.env" \
  && fail "a Windows line ending was copied" || pass "no Windows line endings are copied"
[ "$(grep -c '^EXPLICIT_FILTER=' "$work/octo/.env")" = 1 ] \
  && pass "no setting is written twice" || fail "a setting is written twice"
grep -q '^YTDLP_MAX_CONCURRENT=5$' "$work/octo/.env" \
  && pass "defaults the old .env lacked are added" || fail "a missing default was not added"
# Only where the file system keeps Unix permissions at all.
touch "$work/probe" && chmod 600 "$work/probe"
if [ "$(stat -c %a "$work/probe" 2>/dev/null)" = 600 ]; then
  [ "$(stat -c %a "$work/octo/.env")" = 600 ] && pass ".env is readable by its owner only" || fail ".env is not chmod 600"
fi

cp "$work/octo/.env" "$work/first.env"
run
cmp -s "$work/first.env" "$work/octo/.env" \
  && pass "running it again changes nothing" || { fail "a second run changed .env:"; diff "$work/first.env" "$work/octo/.env"; }

# A first install takes the defaults the questions show.
fresh
run
for want in SUBSONIC_URL=http://192.168.1.10:4533 "DOWNLOAD_PATH=$work/octo/downloads" \
    DOWNLOAD_SOURCE=Soulseek STORAGE_MODE=Stream FOLDER_STRUCTURE=Flat SLSKD_USERNAME=admin \
    LIDARR_QUALITY_PROFILE_ID=0 LIDARR_COMPLETION_MODE=Accepted EXPLICIT_FILTER=All; do
  grep -qx "$want" "$work/octo/.env" && pass "a first install writes $want" || fail "a first install did not write $want"
done
[ -n "$(value_of "$work/octo/.env" SLSKD_PASSWORD)" ] \
  && pass "a first install makes an slskd password" || fail "no slskd password on a first install"
grep -q 'Kept from your earlier' "$work/octo/.env" \
  && fail "a first install has a kept section" || pass "a first install has nothing to keep"

# An older installer wrote some settings empty; a re-run fills them with their defaults.
fresh
printf 'SUBSONIC_URL=http://192.168.1.20:4533\nDOWNLOAD_PATH=%s\nLIDARR_COMPLETION_MODE=\nSLSKD_USERNAME=\n' \
  "$work/music" > "$work/octo/.env"
run
grep -qx 'LIDARR_COMPLETION_MODE=Accepted' "$work/octo/.env" && grep -qx 'SLSKD_USERNAME=admin' "$work/octo/.env" \
  && pass "settings an older installer left empty get their defaults" || fail "empty settings stayed empty"

echo
[ "$failures" = 0 ] && echo "All installer tests passed." || echo "$failures installer test(s) failed."
[ "$failures" = 0 ]
