#!/usr/bin/env bash
# Tests that re-running install.sh keeps everything the user had in .env. Runs a copy of the
# installer in a throwaway folder with docker, curl, clear and sleep faked, answering every
# question with Enter, so it runs anywhere bash does (CI runs it beside shellcheck).
#   scripts/test-install.sh
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
installer="$here/../install.sh"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/bin" "$work/music"
failures=0

# docker only logs, and fails the pull of any service FAKE_NO_IMAGE names (no network to
# ghcr.io). curl answers 200 to every status code probe and a Last.fm track to the key check,
# so each question takes the default and Octo looks healthy straight away; with
# FAKE_SLOW_SLSKD=N, Octo's status says slskd is not ok for its first N answers, and with
# FAKE_SONIC_DOWN it says octo-sonic is not ok (an empty music folder) every time.
cat > "$work/bin/docker" <<EOF
#!/usr/bin/env bash
echo "docker \$*" >> "$work/docker.log"
if [ "\$2" = pull ]; then
  for service in \${FAKE_NO_IMAGE:-}; do [ "\$3" = "\$service" ] && exit 1; done
fi
exit 0
EOF
cat > "$work/bin/curl" <<'EOF'
#!/usr/bin/env bash
for arg in "$@"; do
  [ "$arg" = -w ] && { echo 200; exit 0; }
done
case "$*" in
  *audioscrobbler*) echo '{"track":{}}' ;;
  */api/admin/status*)
    calls="$(( $(cat "$FAKE_STATUS_CALLS" 2>/dev/null || echo 0) + 1 ))"
    echo "$calls" > "$FAKE_STATUS_CALLS"
    if [ "$calls" -le "${FAKE_SLOW_SLSKD:-0}" ]; then ok=false; else ok=true; fi
    sonic=true; [ -z "${FAKE_SONIC_DOWN:-}" ] || sonic=false
    echo "{\"services\":{\"slskd\":{\"ok\":$ok,\"configured\":true},\"sonic\":{\"ok\":$sonic,\"configured\":true}}}" ;;
  *) echo '{}' ;;
esac
EOF
printf '#!/usr/bin/env bash\nexit 0\n' > "$work/bin/clear"
printf '#!/usr/bin/env bash\nexit 0\n' > "$work/bin/sleep"
chmod +x "$work/bin/"*
export PATH="$work/bin:$PATH" FAKE_STATUS_CALLS="$work/status-calls"

fresh() { # a copy of the installer with no .env yet
  rm -rf "$work/octo"
  mkdir -p "$work/octo/scripts/updater"
  tr -d '\r' < "$installer" > "$work/octo/install.sh"
  # Where systemd runs (CI does), the installer offers the update helper; never install it here.
  printf '#!/usr/bin/env bash\nexit 0\n' > "$work/octo/scripts/updater/install-updater.sh"
  chmod +x "$work/octo/install.sh" "$work/octo/scripts/updater/install-updater.sh"
}
printf '\n%.0s' $(seq 1 50) > "$work/answers"
run() { # answers every question with Enter
  : > "$work/docker.log"
  rm -f "$FAKE_STATUS_CALLS"
  bash "$work/octo/install.sh" < "$work/answers" > "$work/out.log" 2>&1
}
# What the run pulled and built, as "pull a b | build c d".
images() {
  printf '%s | %s' "$(sed -n 's/^docker compose pull //p' "$work/docker.log" | paste -sd ' ' -)" \
    "$(sed -n 's/^docker compose \(--profile source \)\{0,1\}build //p' "$work/docker.log")"
}
expect_images() { # name, wanted images line
  [ "$(images)" = "$2" ] && pass "$1" || fail "$1: $(images) (want $2)"
}
# A setting's value as Compose reads it: the last line wins, surrounding quotes come off.
value_of() {
  local line
  line="$(tr -d '\r' < "$1" | grep "^$2=" | tail -n 1)" || return 1
  line="${line#*=}"; line="${line%\"}"; echo "${line#\"}"
}
pass() { echo "ok    $1"; }
fail() { echo "FAIL  $1"; failures=$((failures + 1)); }

# An .env the way a user who has been running Octo a while might have it: everything the
# installer asks about, a default changed by hand, settings the installer has never written,
# an empty value, a value with = in it, quotes, a Windows line ending and no final newline.
fresh
cat > "$work/octo/.env" <<EOF
# Generated by install.sh, then edited by hand.
SUBSONIC_URL=http://192.168.1.20:4533
DOWNLOAD_PATH=$work/music
LASTFM_API_KEY=abc123
LASTFM_API_SECRET=s3cret=with=equals
LASTFM_ENABLE_DISCOVERY_MIX=false
LASTFM_ENABLE_YOUR_MIX=false
LASTFM_DISCOVERY_STATION_COUNT=4
LASTFM_PERSONALIZED_STATION_COUNT=6
LASTFM_RADIO_TRACK_COUNT=80
SLSKD_USERNAME=octoadmin
SLSKD_PASSWORD=webpass
SLSKD_SEARCH_WAIT_SECONDS="12"
SLSKD_SOULSEEK_USERNAME=someone
SLSKD_SOULSEEK_PASSWORD="pass word"
DOWNLOAD_SOURCE=Soulseek
STORAGE_MODE=Permanent
FOLDER_STRUCTURE=Organized
EXPLICIT_FILTER=Clean
YTDLP_GATE_RESERVE=2
YTDLP_BG_GATE_WAIT_SEC=45
OCTO_CONFIG_DIR=$work/octo-config
UPDATES_CHECK=false
UPDATES_REPO=
COMPOSE_PROFILES=sonic
EOF
printf 'Custom_Key2=kept\r\nLAST_LINE=no-newline' >> "$work/octo/.env"
cp "$work/octo/.env" "$work/before.env"

run && pass "the installer finishes" || { fail "the installer stopped early:"; tail -n 20 "$work/out.log"; }

lost=()
for key in $(grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$work/before.env" | tr -d '=' | sort -u); do
  want="$(value_of "$work/before.env" "$key")"
  got="$(value_of "$work/octo/.env" "$key")" || got="(missing)"
  [ "$got" = "$want" ] || lost+=("$key: had '$want', now '$got'")
done
[ "${#lost[@]}" = 0 ] && pass "every setting in the old .env keeps its value" || {
  fail "settings lost or changed:"; printf '        %s\n' "${lost[@]}"; }

grep -qx 'EXPLICIT_FILTER=Clean' "$work/octo/.env" && grep -qx 'LASTFM_RADIO_TRACK_COUNT=80' "$work/octo/.env" \
  && pass "a default changed by hand stays changed" || fail "a hand-changed default went back"
grep -qx 'SLSKD_SEARCH_WAIT_SECONDS="12"' "$work/octo/.env" \
  && pass "a kept line keeps its quotes" || fail "a kept line lost its quotes"
grep -qx 'UPDATES_REPO=' "$work/octo/.env" \
  && pass "an empty value is kept" || fail "an empty value was dropped"
grep -q $'\r' "$work/octo/.env" \
  && fail "a Windows line ending was copied" || pass "no Windows line endings are copied"
[ "$(grep -c '^EXPLICIT_FILTER=' "$work/octo/.env")" = 1 ] \
  && pass "no setting is written twice" || fail "a setting is written twice"
grep -q '^YTDLP_MAX_CONCURRENT=5$' "$work/octo/.env" \
  && pass "defaults the old .env lacked are added" || fail "a missing default was not added"
# Only where the file system keeps Unix permissions at all.
touch "$work/probe" && chmod 600 "$work/probe"
if [ "$(stat -c %a "$work/probe" 2>/dev/null)" = 600 ]; then
  [ "$(stat -c %a "$work/octo/.env")" = 600 ] && pass ".env is readable by its owner only" || fail ".env is not chmod 600"
fi

cp "$work/octo/.env" "$work/first.env"
run
cmp -s "$work/first.env" "$work/octo/.env" \
  && pass "running it again changes nothing" || { fail "a second run changed .env:"; diff "$work/first.env" "$work/octo/.env"; }

# A first install takes the defaults the questions show: no Navidrome yet, so the starter stack.
fresh
run
for want in SUBSONIC_URL=http://navidrome:4533 COMPOSE_PROFILES=navidrome SUBSONIC_ADMIN_USERNAME=admin "DOWNLOAD_PATH=$work/octo/downloads" \
    DOWNLOAD_SOURCE=Soulseek STORAGE_MODE=Stream FOLDER_STRUCTURE=Flat SLSKD_USERNAME=admin \
    LIDARR_QUALITY_PROFILE_ID=0 LIDARR_COMPLETION_MODE=Accepted EXPLICIT_FILTER=All; do
  grep -qx "$want" "$work/octo/.env" && pass "a first install writes $want" || fail "a first install did not write $want"
done
[ -n "$(value_of "$work/octo/.env" SLSKD_PASSWORD)" ] \
  && pass "a first install makes an slskd password" || fail "no slskd password on a first install"
grep -q 'Kept from your earlier' "$work/octo/.env" \
  && fail "a first install has a kept section" || pass "a first install has nothing to keep"

# An older installer wrote some settings empty; a re-run fills them with their defaults.
fresh
printf 'SUBSONIC_URL=http://192.168.1.20:4533\nDOWNLOAD_PATH=%s\nLIDARR_COMPLETION_MODE=\nSLSKD_USERNAME=\n' \
  "$work/music" > "$work/octo/.env"
run
grep -qx 'LIDARR_COMPLETION_MODE=Accepted' "$work/octo/.env" && grep -qx 'SLSKD_USERNAME=admin' "$work/octo/.env" \
  && pass "settings an older installer left empty get their defaults" || fail "empty settings stayed empty"

# Octo and the sidecars are pulled and nothing is built; one that will not pull is built instead.
fresh
run
expect_images "Octo and the sidecars are pulled, nothing is built" "octo yt-dlp-shim octo-sonic | "
grep -q 'compose up -d' "$work/docker.log" && pass "the stack is started" || fail "the stack was not started"
FAKE_NO_IMAGE=octo run
expect_images "Octo that will not pull is built from the folder" "octo yt-dlp-shim octo-sonic | octo-source"
grep -q 'could not pull octo, so it is built' "$work/out.log" && pass "the installer says Octo is built here" || fail "the installer did not say Octo is built here"
FAKE_NO_IMAGE=octo-sonic run
expect_images "a sidecar that will not pull is built from the folder" "octo yt-dlp-shim octo-sonic | octo-sonic-source"
FAKE_NO_IMAGE="octo yt-dlp-shim octo-sonic" run && pass "without ghcr.io the installer still finishes" || fail "without ghcr.io the installer stopped"
expect_images "without ghcr.io everything is built" "octo yt-dlp-shim octo-sonic | octo-source yt-dlp-shim-source octo-sonic-source"

# In a git checkout, an image whose folder changed since the release the folder names is built,
# because its published image is not what the folder holds: Octo's own code, its Dockerfile, or
# a sidecar. One the user pinned with OCTO_IMAGE_TAG is pulled anyway.
fresh
(
  cd "$work/octo" || exit 1
  mkdir -p octo yt-dlp-shim sonic
  printf '<InformationalVersion>2026.10.05</InformationalVersion>\n' > octo/octo.csproj
  echo one > octo/Program.cs && echo one > Dockerfile
  echo one > yt-dlp-shim/app.py && echo one > sonic/main.rs
  git init -q . && git config core.autocrlf false && git add -A && git -c user.email=t@example.com -c user.name=t commit -qm release && git tag 2026.10.05
) || fail "could not make the test checkout"
run
expect_images "a checkout of the release pulls all three" "octo yt-dlp-shim octo-sonic | "
echo two > "$work/octo/yt-dlp-shim/app.py"
run
expect_images "a shim changed since the release is built" "octo octo-sonic | yt-dlp-shim-source"
git -C "$work/octo" checkout -q -- yt-dlp-shim
echo two > "$work/octo/octo/Program.cs"
run
expect_images "Octo changed since the release is built, never pulled over" "yt-dlp-shim octo-sonic | octo-source"
grep -q 'octo changed since its release, so it is built from this folder' "$work/out.log" \
  && pass "the installer says why Octo is built" || fail "the installer did not say why Octo is built"
git -C "$work/octo" checkout -q -- octo
echo two > "$work/octo/Dockerfile"
run
expect_images "a changed Dockerfile builds Octo" "yt-dlp-shim octo-sonic | octo-source"
echo "OCTO_IMAGE_TAG=latest" >> "$work/octo/.env"
run
expect_images "a tag the user chose is pulled" "octo yt-dlp-shim octo-sonic | "

# Octo answers within seconds now that it is pulled; a service still starting is waited for.
fresh
FAKE_SLOW_SLSKD=2 run
grep -q 'waiting for the other services to start' "$work/out.log" && grep -Eq 'slskd +.*ok' "$work/out.log"   && pass "a service still starting is waited for, then shown ok" || { fail "slskd still starting:"; grep -E 'waiting|slskd  ' "$work/out.log"; }
fresh
run
grep -q 'waiting for the other services' "$work/out.log"   && fail "the installer waited with every service ok" || pass "with every service ok the installer does not wait"
fresh
FAKE_SONIC_DOWN=1 run
grep -q 'waiting for the other services' "$work/out.log"   && fail "the installer waited for octo-sonic on an empty music folder" || pass "octo-sonic on an empty music folder is not waited for"

# The installer's answer decides only the navidrome profile; any other profile stays.
fresh
printf 'SUBSONIC_URL=http://navidrome:4533\nDOWNLOAD_PATH=%s\nCOMPOSE_PROFILES=sonic,navidrome\n' "$work/music" > "$work/octo/.env"
run
grep -qx 'COMPOSE_PROFILES=sonic,navidrome' "$work/octo/.env" \
  && pass "a starter stack keeps its profiles" || fail "starter profiles: $(grep COMPOSE_PROFILES "$work/octo/.env")"

echo
[ "$failures" = 0 ] && echo "All installer tests passed." || echo "$failures installer test(s) failed."
[ "$failures" = 0 ]
